name: Update

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 6 * * *'

jobs:
  Update:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependancies
      run: |
        pip install wheel
        python setup.py bdist_wheel
        pip install -r requirements.txt
        pip install dist/rankingbot-*.whl
    - name: Update
      run: python -m rankingbot
      env:
        RANKINGBOT_PASSWORD: ${{ secrets.RANKINGBOT_PASSWORD }}
