name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache python modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install flake8 pytest pytest-cov
          python -m pip install wheel
          python setup.py bdist_wheel
          python -m pip install dist/rankingbot-*.whl

      - name: Lint
        run: flake8 -v

      - name: Test
        run: pytest --cov-report=xml --cov=./
        env:
          BOT_TEST: '1'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
